/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 caza-v1.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/caza-v1.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="caza-rigg" rotation={[Math.PI / 2, 0, 0]}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Armas_0001" geometry={nodes.Armas_0001.geometry} material={materials.Armas} skeleton={nodes.Armas_0001.skeleton} />
          <skinnedMesh name="Balas_0001" geometry={nodes.Balas_0001.geometry} material={materials.Balas} skeleton={nodes.Balas_0001.skeleton} />
          <skinnedMesh name="Bolcillos_0001" geometry={nodes.Bolcillos_0001.geometry} material={materials.Bolsillos} skeleton={nodes.Bolcillos_0001.skeleton} />
          <skinnedMesh name="Botas_0001" geometry={nodes.Botas_0001.geometry} material={materials.Botas} skeleton={nodes.Botas_0001.skeleton} />
          <skinnedMesh name="Cabeza_0001" geometry={nodes.Cabeza_0001.geometry} material={materials.Cabeza} skeleton={nodes.Cabeza_0001.skeleton} />
          <skinnedMesh name="Calavera_0001" geometry={nodes.Calavera_0001.geometry} material={materials.Calavera} skeleton={nodes.Calavera_0001.skeleton} />
          <skinnedMesh name="Cartucheras_0001" geometry={nodes.Cartucheras_0001.geometry} material={materials.Cartucheras} skeleton={nodes.Cartucheras_0001.skeleton} />
          <skinnedMesh name="Cinturon_0001" geometry={nodes.Cinturon_0001.geometry} material={materials.Cinturon} skeleton={nodes.Cinturon_0001.skeleton} />
          <skinnedMesh name="Cuerpo_0001" geometry={nodes.Cuerpo_0001.geometry} material={materials.Cuerpo} skeleton={nodes.Cuerpo_0001.skeleton} />
          <skinnedMesh name="Manos_0001" geometry={nodes.Manos_0001.geometry} material={materials.Manos} skeleton={nodes.Manos_0001.skeleton} />
          <skinnedMesh name="MateGranadas_0001" geometry={nodes.MateGranadas_0001.geometry} material={materials.MateGranada} skeleton={nodes.MateGranadas_0001.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/caza-v1.glb')
